# shopify.app.toml

name = "Schulbox Konfigurator"
client_id = "15d4e4981c4a7b8936f83ba81e11cad7"
application_url = "https://schulbox-konfigurator.vercel.app"
embedded = true

[auth]
redirect_urls = [
  "https://schulbox-konfigurator.vercel.app/api/auth/callback"
]

[access_scopes]
scopes = "read_products,write_products"

[webhooks]
api_version = "2023-10"
